export const UPDATE_STATIONS = 'UPDATE_STATIONS';
export const LOCATION_CHANGE = 'LOCATION_CHANGE';
export const STOP_TRACKING = 'STOP_TRACKING';
export const START_TRACKING = 'START_TRACKING';
export const SEARCH_COMPLETED = 'SEARCH_COMPLETED';
export const SEARCH_STARTED = 'SEARCH_STARTED';